Module2 task1
htmlacademy-adaptive/2098917-sedona-27 pull request #2
Opened 2022-11-27 19:21 UTC by MissShim

Привет! 
Валидатор html и йоксель мне проблем не показали.
Но не могу похвастаться, что БЭМ стал мне кристально понятен после этого раздела. Я пока поделила всё на блоки-элементы-модификаторы по минимуму. Предполагаю, что в процессе написания css станет понятнее, где нужно дополнительно выделять блоки и элементы, а где нет. Надеюсь, это ок?
Кузьмина Полина.

2022-11-29 12:41 UTC, pavel-nyukalo requested changes

2022-11-29 12:41 UTC, pavel-nyukalo commented on source/index.html
> +      <img class="main-nav__logo-image" src="../images/index/header-logo.png" width="185" height="96" alt="City of Sedona">
`html` файлы у нас находятся на одном уровне с папкой `images`, поэтому тут не надо выходить на уровень выше, и лучше писать src="images/..."

2022-11-29 12:41 UTC, pavel-nyukalo commented on source/index.html
> +        </svg>
Это мы через фоновую картинку вставим, так что отсюда давай уберем

2022-11-29 12:41 UTC, pavel-nyukalo commented on source/index.html
> +      </div>
Насчет списка
1. Давай иконки жилья, еды и сувениров сделаем так же через фоновые, они больше на декор похожи
2. А вот преимущества похожи на список, причем нумерованный

![image](https://user-images.githubusercontent.com/52506235/204530079-b42c9b8c-d6ae-4f67-9ee9-40fcbd1e66cf.png)

Красный - `ol`
Зеленый - `li` этого `ol`
Синий - `ul` внутри первого `li` у `ol`
Фиолетовый - `li` внутри `ul` 

Если что пиши - разберем

2022-11-29 12:41 UTC, pavel-nyukalo commented on source/form.html
> +        </div>
В фоновую картинку

2022-11-29 12:41 UTC, pavel-nyukalo commented on source/catalog.html
> +            <img class="photo-card__photo" src="../images/catalog/photo-1-mobile.jpg" width="280" height="280" alt="Уходящая в закат дорога">
Изображения [должны быть](https://up.htmlacademy.ru/adaptive/27/project/sedona#sedona-6-1) ссылками

2022-11-29 12:41 UTC, pavel-nyukalo commented on source/catalog.html
> +          </a>
В идеале тут будет тег `video`, но достаточно просто картинки, без ссылки

2022-11-29 17:28 UTC, MissShim commented on source/catalog.html
> +                <input class="likes__counter" type="number" value="1350">
я сделала через инпут, потому что нашла туториал, "как делать счётчики лайков" на ютубе. А если не через инпуты, то как потом лайки будут считаться?

2022-11-29 17:37 UTC, MissShim commented on source/index.html
> +      <img class="main-nav__logo-image" src="../images/index/header-logo.png" width="185" height="96" alt="City of Sedona">
Эти файлы разве не должны быть в папке source, которая находится на одном уровне с images? Это в требованиях к текущей домашке указано: "HTML-страницы должны лежать в папке source." (с) По учебнику получается, что можно записать или через ../ (выходим из source, заходим в images) или через / (от корня). Если я запишу через "/images/index...", примите?

2022-12-02 12:12 UTC, pavel-nyukalo commented on source/catalog.html
> +                <input class="likes__counter" type="number" value="1350">
Через JS. ТАм будет обработчки, который будет просто увеличивать на один кол-во лайков.

Просто тут немного логика нарушается

Мы отображаем сколько людей лайкнуло эту фотографию. При этом мы можем поставить или снять поставленный нами лайк. За это как раз кнопочка отвечает. А значение в инпуте мы можем менять сколько нам угодно, и немного с бизнес логикой противоречивость

2022-12-02 12:22 UTC, pavel-nyukalo commented on source/index.html
> +        </div>
Про это выше писал - давай сделаем списком, а декоративные картинки уберем из разметки. Пока не буду закрывать [комментарий](https://github.com/htmlacademy-adaptive/2098917-sedona-27/pull/2#discussion_r1034696798), чтобы можно было на него опираться

2022-12-04 12:08 UTC, pavel-nyukalo requested changes

2022-12-04 13:48 UTC, pavel-nyukalo approved these changes

2022-12-04 13:49 UTC, merged