Module3 task1
htmlacademy-adaptive/2098917-sedona-27 pull request #3
Opened 2022-12-14 12:40 UTC by MissShim

Готовлюсь к исправлениям :)

2022-12-15 10:17 UTC, pavel-nyukalo requested changes

2022-12-15 10:17 UTC, pavel-nyukalo commented on source/less/blocks/main-header.less
> +}
`main-nav`, `menu-button` и `close-button` уже отдельные БЭМ-блоки, поэтому им нужны свои файлы - `main-nav.less`, `menu-button.less` и `close-button.less`.

Но опять же можно подумать надо ли нам `menu-button.less` и `close-button.less`? Может застилизовать в `main-nav__toggle` и `main-nav__close`?

2022-12-15 10:17 UTC, pavel-nyukalo commented on source/less/blocks/main-header.less
> +.main-nav__list-wrapper--hidden {
Это соответственно тоже уйдет в `main-nav.less`

2022-12-15 10:17 UTC, pavel-nyukalo commented on source/less/blocks/photos.less
> +}
Тоже отдельный БЭМ-блок - в свой файл

2022-12-15 10:17 UTC, pavel-nyukalo commented on source/less/blocks/success.less
> +.modal-success {
Эти стили отсюда надо удалить - этот файл у нас для `success`. Плюс они уже есть в `modal-success.less`

2022-12-15 10:17 UTC, pavel-nyukalo commented on source/less/blocks/success.less
> +.success-window {
А этому нужен так же свой файл

2022-12-15 10:17 UTC, pavel-nyukalo commented on source/less/blocks/vars.less
> +}
Так понимаю, этот файл уже не нужен?

`visually-hidden` описан в `visually-hidden.less`, а `header` в `vars.less`

2022-12-17 14:31 UTC, MissShim commented on source/less/blocks/vars.less
> +}
Ты имеешь в виду, что не нужен файл vars.less? Сейчас там одна переменная header() с общими стилями для всех заголовков. Я её сделала просто для эксперимента. Посмотреть, как работают переменные. Эта переменная используется в разных блоках сайта, почему этот файл надо удалить?

2022-12-20 07:42 UTC, pavel-nyukalo approved these changes

2022-12-20 07:42 UTC, merged