added files anew
htmlacademy-adaptive/2098917-sedona-27 pull request #5
Opened 2022-12-27 15:07 UTC by MissShim

Заново добавила все, что сделала раньше.
Про то, что сделала:
Я вроде почти всё закончила, кроме того, что не сверяла размеры элементов через пиксель перфект, и ещё не прочитала разделы курса про графику, так что не знаю, насколько правильно у меня графика вставлена. Буду читать и сверять.
Но на счёт адаптивности, всё вроде работает, хотя "резиновость" не везде получилась. Вот только, я не везде использвала медиа-запрос для десктопа. Так можно? Потому что и без него пока все хорошо работает.

2022-12-28 13:49 UTC, pavel-nyukalo requested changes

2022-12-28 13:49 UTC, pavel-nyukalo commented on source/index.html
> +        <li class="advantages__item grid__three">
Здесь бы конечно не разбивать на два пункта, поскольку картинка все же относится к описанию

Можно растянуть весь `li` на три колонки и в нем сетку построить

2022-12-28 13:49 UTC, pavel-nyukalo commented on source/less/blocks/advantages.less
> +    box-shadow: inset 1px -162px 0 30px #eeeeee;
Интересное решение, но не очень надежное. Чуть добавить текста и все поедет

![image](https://user-images.githubusercontent.com/52506235/209819025-9b68121f-ba1c-41d7-b1e7-3d9288cf027c.png)

2022-12-28 13:49 UTC, pavel-nyukalo commented on source/less/blocks/advantages.less
> +    height: 260px;
Лучше задавать `min-height`, поскольку жестко заданная высота не пройдет переполнение

![image](https://user-images.githubusercontent.com/52506235/209819688-5c9643b1-585b-4953-8e51-c4580f22c976.png)

Но и это не все, даже если мы зададим `min-`, карточка как будто выпала

![image](https://user-images.githubusercontent.com/52506235/209819769-61d9a968-c839-4898-ad44-7b312d4525a5.png)

Поэтому варианта два

1. Задавать фоновый цвет не `div`, а `li` - тогда если одна карточка растянется, она растянет грид-строку и соответственно, другие `li` так же растянутся и будут уже закрашенными
2. Дать `div` внутри этих `li` `flex-grow: 1` - чтобы они растягивались на всю высоту растянувшихся `li`

2022-12-28 13:49 UTC, pavel-nyukalo commented on source/less/blocks/attractions.less
> +    grid-template-columns: 1fr 1fr 1fr 1fr;
Можно сократить до `grid-template-columns: repeat(4, 1fr);`

2022-12-28 13:49 UTC, pavel-nyukalo commented on source/less/blocks/hero.less
> +  .hero__img-secondary {
`hero-img` и `hero__img` - разные БЭМ-сущности. Стоит привести к единообразию (поскольку сейчас для `hero-img` нужен свой файл)

2022-12-28 13:49 UTC, pavel-nyukalo commented on source/less/blocks/page.less
> +    5px 0 20px 0 rgba(0, 0, 0, 0.3);
Там чуть другая тень на макете

![image](https://user-images.githubusercontent.com/52506235/209820693-c340802c-cd23-4cc2-872e-8c6273110231.png)

И плюс фоновый цвет `#f2f2f2`

![image](https://user-images.githubusercontent.com/52506235/209820769-84b38854-fe65-4ef5-ba3d-1573e1867ea8.png)

2022-12-28 13:49 UTC, pavel-nyukalo commented on source/less/blocks/photo-grid.less
> +  }
Вот как раз про то что это лучше сделать элементом этого блока

2022-12-28 15:59 UTC, MissShim commented on source/catalog.html
> +          <li class="photos__item photo-card photo-grid-one">
ой да, я так и собиралась, но вечно путаю дефисы с нижним подчеркиванием, спасибо! 😓

2022-12-28 16:01 UTC, MissShim commented on source/less/blocks/advantages.less
> +    box-shadow: inset 1px -162px 0 30px #eeeeee;
если честно, мне просто ничего больше в голову не пришло. Через псевдоэлемент нормально будет сделать?

2023-01-07 11:40 UTC, pavel-nyukalo commented on source/less/blocks/advantages.less
> +    box-shadow: inset 1px -162px 0 30px #eeeeee;
Через `border`, как ты сделала, даже лучше

2023-01-07 11:58 UTC, pavel-nyukalo requested changes

2023-01-07 11:58 UTC, pavel-nyukalo commented on source/index.html
> +            <div class="advantages__numbered-text">
Могут придраться что много дивов. Я бы попробовал сократить (хотя бы что бы вот так осталось)

```html
<li>
  <div>
    <p></p>
    <p></p>
    <p></p>
  </div>
  ...
</li>
```

Плюс

2023-01-07 11:58 UTC, pavel-nyukalo commented on source/index.html
> +            </div>
И еще насчет переполнения

Вот эти хорошо тянуться

![image](https://user-images.githubusercontent.com/52506235/211149050-7e21fd2c-4dd2-4de0-9aa5-50e9d40bfcf7.png)

(единственное, наверное можно сделать вот так, но это уже чисто вкусовщина)

![image](https://user-images.githubusercontent.com/52506235/211149067-8e40c1ed-aed9-48bb-986e-07003f94c977.png)

А вот тут для единообразия я бы тоже сделал, чтобы они вниз растягивались

![image](https://user-images.githubusercontent.com/52506235/211149101-194fb1ed-c645-4c2b-be29-8f131ddc8300.png)

Как-нибудь так например

![image](https://user-images.githubusercontent.com/52506235/211149114-7f23c3a5-58e6-4536-8fb4-7e3dfa57d842.png)

2023-01-07 11:58 UTC, pavel-nyukalo commented on source/index.html
> +        <li class="advantages__item grid__three">
Тут вот не поправлено - разделять картинку и текст на два разных пункта (два отдельных `li`) - не семантично, поскольку текст относится к картинке

2023-01-07 11:58 UTC, pavel-nyukalo commented on source/index.html
> +            <div class="advantages__numbered-text">
Вот эти дивы тоже кажутся лишними, стоит сократить их кол-во

2023-01-07 11:58 UTC, pavel-nyukalo commented on source/less/blocks/advantages.less
> +  }
Тут немного странная запись, должно быть как тут

![image](https://user-images.githubusercontent.com/52506235/211149357-65e07b3b-5e6f-4087-8c76-0e011b1ca053.png)

То есть `&` ссылается на родительский селектор

Например,

```scss
.advantages__numbered {
  padding: 52px 50px;
  
  &....
}

Сошлется на `advantages__numbered`. А если их вот так разделить, то ему не на что будет ссылаться, и оно не отработает

![image](https://user-images.githubusercontent.com/52506235/211149433-b925146f-2ca3-4091-b2f9-9df9e71203e5.png)

2023-01-07 11:58 UTC, pavel-nyukalo commented on source/less/blocks/hero.less
> +  }
Вот эту запись нужно удалить сейчас

2023-01-07 11:58 UTC, pavel-nyukalo commented on source/less/blocks/main-nav.less
> +  }
В разметке у нас вроде бы таких селекторов уже нет? Тогда нужно отсюда тоже удалить

2023-01-09 11:49 UTC, pavel-nyukalo approved these changes

2023-01-09 11:49 UTC, merged