Module6 task1
htmlacademy-adaptive/2098917-sedona-27 pull request #7
Opened 2023-01-15 09:29 UTC by MissShim

- произвела ретинизацию;
- сделала контентные изображения адаптивными;
- подключила к проекту фавиконки.
Вроде все, как должно быть :)

2023-01-15 16:29 UTC, pavel-nyukalo requested changes

2023-01-15 16:29 UTC, pavel-nyukalo commented on source/catalog.html
> +  <link rel="icon" href="../favicon.ico">
`favicon` нам нужно положить в `source/` (и соответственно путь изменится на просто `href="favicon.ico"`

![image](https://user-images.githubusercontent.com/52506235/212552494-e49efb61-e4ac-4bda-ace9-9fb7874b20ea.png)

2023-01-15 16:29 UTC, pavel-nyukalo commented on source/catalog.html
> +  <link rel="manifest" href="manifest.webmanifest">
Если подключаем манифест, то его нужно создать тоже

2023-01-15 16:29 UTC, pavel-nyukalo commented on source/catalog.html
> +          <source media="(min-width: 320px)" srcset="img/form/sedona-small.png">
Если правильно понял, эта картинка у нас подключена в `img`. Тогда делать для нее еще одни `source` нет смысла

Кстати, по идее нам тут нужно делать тоже ретинизацию (поскольку `png`). Но я бы предложил экспортировать эту надпись в виде `svg`. Тогда уже не надо будет ретинизацию делать

2023-01-15 16:29 UTC, pavel-nyukalo commented on source/catalog.html
> +        <img class="main-header__logo-image" srcset="img/index/header-logo-280.png 1x, img/index/header-logo-x2.png 2x" width="185" height="96" alt="City of Sedona">
Тут так же наверное лучше сделать через `svg`, чтобы не экспортировать две картинки

2023-01-15 16:29 UTC, pavel-nyukalo commented on source/catalog.html
> +                <img class="photo-card__first" src="img/catalog/photo-1-mobile.jpg" width="280" height="280" alt="Уходящая в закат дорога">
`<source media="(min-width: 320px)"` по сути лишний. `img/catalog/catalog/mobile/photo-1-mobile@1x.jpg` - это по сути же `img/catalog/photo-1-mobile.jpg`, которая в `img` подключена?

Тут можно мобильные подключить в `img`, а в `source` уже планшетные и декстопные

Получится что-то типа

```html
<source media="(min-width: 1200px)" srcset="img/catalog/catalog/desktop/photo-1-desktop@1x.jpg 1x, img/catalog/catalog/desktop/photo-1-desktop@2x.jpg 2x">
<source media="(min-width: 768px)" srcset="img/catalog/catalog/tablet/photo-1-tablet@1x.jpg 1x, img/catalog/catalog/tablet/photo-1-tablet@2x.jpg 2x">
<img class="photo-card__first" src="img/catalog/catalog/mobile/photo-1-mobile@1x.jpg" srcset="img/catalog/catalog/mobile/photo-1-mobile@2x.jpg 2x" width="280" height="280" alt="Уходящая в закат дорога">
```

2023-01-15 16:29 UTC, pavel-nyukalo commented on source/catalog.html
> +                <source media="(min-width: 320px)" srcset="img/catalog/catalog/mobile/photo-2-mobile@1x.jpg 1x, img/catalog/catalog/mobile/photo-2-mobile@2x.jpg 2x">
Ну и с остальными аналогично

2023-01-15 16:29 UTC, pavel-nyukalo commented on source/img/favicons/browserconfig.xml
> +<?xml version="1.0" encoding="utf-8"?>
Интересный файл, это где-то в материалах было?

2023-01-15 16:29 UTC, pavel-nyukalo commented on source/img/favicons/manifest.json
> +{
А, вот этот манифест. Его нужно переместить в `source/` (и пути проверить соответственно)

2023-01-15 16:29 UTC, pavel-nyukalo commented on source/img/index/text-index.svg@2x.svg
> +<svg width="461" height="350" viewBox="0 0 461 350" fill="none" xmlns="http://www.w3.org/2000/svg">
Вот эти картинки как раз есть в `svg`, но в разметке идет `png`

![image](https://user-images.githubusercontent.com/52506235/212553116-ce76e67b-4734-41ea-b72b-34fd03bd356c.png)

И тут пару моментов  
Первое, лучше просто назвать `...index.svg`

![image](https://user-images.githubusercontent.com/52506235/212553155-9d84bd74-876e-4b86-ab40-98e8818f9862.png)

Второе, 2х для `svg` не нужно (оно по коду ничем не отличается от обычной), поскольку `svg` масштабируемая графика

2023-01-15 16:29 UTC, pavel-nyukalo commented on source/js/script.js
> +    }
Линтер не ругался на отступы?

У нас по сути для всех файлов установлены отступы в 2 пробела

![image](https://user-images.githubusercontent.com/52506235/212553241-bac5b020-3c9d-46f5-bff1-59f28fe60a4a.png)

2023-01-15 16:29 UTC, pavel-nyukalo commented on source/less/blocks/video.less
> +    height: auto;
Дублировать одинаковые свойства (то есть которые не меняются) от брейкпоинта к брейкпоинту нет смысла, поскольку они применятся еще с предыдущего брейкпоинта

То бишь, `display: flex` и `height: auto;` не меняются от планшета - их можно не указывать. Поменялась ширина - ее указываем да в десктопе

2023-01-15 20:54 UTC, MissShim commented on source/catalog.html
> +          <source media="(min-width: 320px)" srcset="img/form/sedona-small.png">
Я уже поняла, что её предполагается оптимизировать, как svg, и скрывать по частям.

2023-01-15 21:01 UTC, MissShim commented on source/img/favicons/browserconfig.xml
> +<?xml version="1.0" encoding="utf-8"?>
скопировала, как было, через favicon-generator, как в статье в разделе говорили. Ничего не трогала.

2023-01-15 21:02 UTC, MissShim commented on source/js/script.js
> +    }
Нет, все замечания линтера я поправила, больше у него вопросов не было.

2023-01-15 21:07 UTC, MissShim commented on source/img/favicons/manifest.json
> +{
а что должно быть с путями? сейчас строчка про манифест такая:
  <link rel="manifest" href="manifest.webmanifest">

а должно быть как, если она в /source? Так? Она же на одном уровне с html-файлами.
  <link rel="manifest" href="manifest.json">

2023-01-16 11:41 UTC, MissShim commented on source/catalog.html
> +          <source media="(min-width: 320px)" srcset="img/form/sedona-small.png">
Я сделала через svg, как в модуле 7, через спрайт

2023-01-16 11:43 UTC, MissShim commented on source/catalog.html
> +                <img class="photo-card__first" src="img/catalog/photo-1-mobile.jpg" width="280" height="280" alt="Уходящая в закат дорога">
ок, это сделаю. А ещё вопрос: я в каталоге для первой, самой большой фотографии добавила webp, все три размера через source. Это нормально, или для мобильной версии webp тоже нужен тег img, а не source?

2023-01-16 11:44 UTC, MissShim commented on source/img/index/text-index.svg@2x.svg
> +<svg width="461" height="350" viewBox="0 0 461 350" fill="none" xmlns="http://www.w3.org/2000/svg">
сделала всё, что делалось, через svg-sprite.

2023-01-16 14:23 UTC, merged